export const dataCard = [
  {
    title: "Jami xorijiy tillarga o'qitiladigan yoshlar soni",
    students: 6932,
    icon: "Users",
  },
  {
    title: "Inglis tiliga o'qitiladigan yoshlar soni ( C1 )",
    students: 4211,
    icon: "BookOpenCheck",
  },
  {
    title: "Inglis tiliga o'qitiladigan yoshlar soni ( B2 )",
    students: 80,
    icon: "BookOpenCheck",
  },
  {
    title: "Nemis tiliga o'qitiladigan yoshlar soni ( C1 )",
    students: 80,
    icon: "BookOpenCheck",
  },
  {
    title: "Nemis tiliga o'qitiladigan yoshlar soni ( B2 )",
    students: 70,
    icon: "BookOpenCheck",
  },
];

export const nodes = [
  {
    id: 1,
    region: "Muborak",
    students: 363,
    englishB: 80,
    englishC: 34,
    nemisB1: 32,
    nemisB2: 34,
    url: "/muborak",
  },
  {
    id: 2,
    region: "Qarshi sh",
    students: 363,
    englishB: 80,
    englishC: 34,
    nemisB1: 32,
    nemisB2: 34,
    url: "/qarshi",
  },
  {
    id: 3,
    region: "Qarshi t",
    students: 363,
    englishB: 80,
    englishC: 34,
    nemisB1: 32,
    nemisB2: 34,
    url: "/qarshi",
  },
  {
    id: 4,
    region: "G'uzor t",
    students: 363,
    englishB: 80,
    englishC: 34,
    nemisB1: 32,
    nemisB2: 34,
    url: "/guzor",
  },
  {
    id: 5,
    region: "Dehqanabot",
    students: 363,
    englishB: 80,
    englishC: 34,
    nemisB1: 32,
    nemisB2: 34,
    url: "/dehqanabot",
  },
  {
    id: 6,
    region: "Qamashi t",
    students: 363,
    englishB: 80,
    englishC: 34,
    nemisB1: 32,
    nemisB2: 34,
    url: "/qamashi",
  },
  {
    id: 7,
    region: "Kasbi t",
    students: 363,
    englishB: 80,
    englishC: 34,
    nemisB1: 32,
    nemisB2: 34,
    url: "/kasbi",
  },
  {
    id: 8,
    region: "Kitob t",
    students: 363,
    englishB: 80,
    englishC: 34,
    nemisB1: 32,
    nemisB2: 34,
    url: "/kitob",
  },
  {
    id: 9,
    region: "Koson t",
    students: 363,
    englishB: 80,
    englishC: 34,
    nemisB1: 32,
    nemisB2: 34,
    url: "/koson",
  },
  {
    id: 10,
    region: "Mirishkor t",
    students: 363,
    englishB: 80,
    englishC: 34,
    nemisB1: 32,
    nemisB2: 34,
    url: "/mirishkor",
  },
  {
    id: 11,
    region: "Nishon t",
    students: 363,
    englishB: 80,
    englishC: 34,
    nemisB1: 32,
    nemisB2: 34,
    url: "/nishon",
  },
  {
    id: 12,
    region: "Shaxrisabz sh",
    students: 363,
    englishB: 80,
    englishC: 34,
    nemisB1: 32,
    nemisB2: 34,
    url: "/shaxrisabz",
  },
  {
    id: 13,
    region: "Shaxrisabz t",
    students: 363,
    englishB: 80,
    englishC: 34,
    nemisB1: 32,
    nemisB2: 34,
    url: "/shaxrisabz",
  },
  {
    id: 14,
    region: "Chiroqchi t",
    students: 363,
    englishB: 80,
    englishC: 34,
    nemisB1: 32,
    nemisB2: 34,
    url: "/chiroqchi",
  },
  {
    id: 15,
    region: "Yakkabog' t",
    students: 363,
    englishB: 80,
    englishC: 34,
    nemisB1: 32,
    nemisB2: 34,
    url: "/yakkabog",
  },
  {
    id: 16,
    region: "Ko'kdala t",
    students: 363,
    englishB: 80,
    englishC: 34,
    nemisB1: 32,
    nemisB2: 34,
    url: "/kokdala",
  },
];

export const columns = [
  "Hududlar",
  "Jami xorijiy tillarga o'qitilishi kerak bo'lgan yoshlar soni",
  "Ingliz tiliga o'qitilishi kerak bo'lgan yoshlar soni (B2)",
  "Ingliz tiliga o'qitilishi kerak bo'lgan yoshlar soni (C1)",
  "Nemis tiliga o'qitilishi kerak bo'lgan yoshlar soni (C1)",
  "Nemis tiliga o'qitilishi kerak bo'lgan yoshlar soni (B2)",
  "Ko'rish",
];
